language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - build-tools-25.0.1
    - build-tools-25.0.2
    - android-28
    - android-27
    - android-22
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

licenses:
  - 'android-sdk-license-.+'
  - 'android-sdk-preview-.+'
  - '.*'

jdk:
  - oraclejdk8

sudo: true

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 10
  - adb shell input keyevent 82

env:
  matrix:
    - TEST=:sample:app:connectedDebugAndroidTest
    - TEST=:activitystarter:test
    - TEST=:activitystarter-compiler:test

script:
  - ./gradlew $TEST -i

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle